version: '3'
services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: university
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123

  spring-app:
    container_name: spring-app
    image: project
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_PORT: 3306
